// Code generated by mockery. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockServiceAddresses is an autogenerated mock type for the ServiceAddresses type
type MockServiceAddresses struct {
	mock.Mock
}

type MockServiceAddresses_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceAddresses) EXPECT() *MockServiceAddresses_Expecter {
	return &MockServiceAddresses_Expecter{mock: &_m.Mock}
}

// Kafka provides a mock function with no fields
func (_m *MockServiceAddresses) Kafka() ServiceAddress {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kafka")
	}

	var r0 ServiceAddress
	if rf, ok := ret.Get(0).(func() ServiceAddress); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServiceAddress)
	}

	return r0
}

// MockServiceAddresses_Kafka_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kafka'
type MockServiceAddresses_Kafka_Call struct {
	*mock.Call
}

// Kafka is a helper method to define mock.On call
func (_e *MockServiceAddresses_Expecter) Kafka() *MockServiceAddresses_Kafka_Call {
	return &MockServiceAddresses_Kafka_Call{Call: _e.mock.On("Kafka")}
}

func (_c *MockServiceAddresses_Kafka_Call) Run(run func()) *MockServiceAddresses_Kafka_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceAddresses_Kafka_Call) Return(_a0 ServiceAddress) *MockServiceAddresses_Kafka_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceAddresses_Kafka_Call) RunAndReturn(run func() ServiceAddress) *MockServiceAddresses_Kafka_Call {
	_c.Call.Return(run)
	return _c
}

// OpenSearch provides a mock function with no fields
func (_m *MockServiceAddresses) OpenSearch() ServiceAddress {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenSearch")
	}

	var r0 ServiceAddress
	if rf, ok := ret.Get(0).(func() ServiceAddress); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServiceAddress)
	}

	return r0
}

// MockServiceAddresses_OpenSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSearch'
type MockServiceAddresses_OpenSearch_Call struct {
	*mock.Call
}

// OpenSearch is a helper method to define mock.On call
func (_e *MockServiceAddresses_Expecter) OpenSearch() *MockServiceAddresses_OpenSearch_Call {
	return &MockServiceAddresses_OpenSearch_Call{Call: _e.mock.On("OpenSearch")}
}

func (_c *MockServiceAddresses_OpenSearch_Call) Run(run func()) *MockServiceAddresses_OpenSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceAddresses_OpenSearch_Call) Return(_a0 ServiceAddress) *MockServiceAddresses_OpenSearch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceAddresses_OpenSearch_Call) RunAndReturn(run func() ServiceAddress) *MockServiceAddresses_OpenSearch_Call {
	_c.Call.Return(run)
	return _c
}

// OpenSearchDashboard provides a mock function with no fields
func (_m *MockServiceAddresses) OpenSearchDashboard() ServiceAddress {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenSearchDashboard")
	}

	var r0 ServiceAddress
	if rf, ok := ret.Get(0).(func() ServiceAddress); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServiceAddress)
	}

	return r0
}

// MockServiceAddresses_OpenSearchDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSearchDashboard'
type MockServiceAddresses_OpenSearchDashboard_Call struct {
	*mock.Call
}

// OpenSearchDashboard is a helper method to define mock.On call
func (_e *MockServiceAddresses_Expecter) OpenSearchDashboard() *MockServiceAddresses_OpenSearchDashboard_Call {
	return &MockServiceAddresses_OpenSearchDashboard_Call{Call: _e.mock.On("OpenSearchDashboard")}
}

func (_c *MockServiceAddresses_OpenSearchDashboard_Call) Run(run func()) *MockServiceAddresses_OpenSearchDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceAddresses_OpenSearchDashboard_Call) Return(_a0 ServiceAddress) *MockServiceAddresses_OpenSearchDashboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceAddresses_OpenSearchDashboard_Call) RunAndReturn(run func() ServiceAddress) *MockServiceAddresses_OpenSearchDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// SchemaRegistry provides a mock function with no fields
func (_m *MockServiceAddresses) SchemaRegistry() ServiceAddress {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SchemaRegistry")
	}

	var r0 ServiceAddress
	if rf, ok := ret.Get(0).(func() ServiceAddress); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServiceAddress)
	}

	return r0
}

// MockServiceAddresses_SchemaRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchemaRegistry'
type MockServiceAddresses_SchemaRegistry_Call struct {
	*mock.Call
}

// SchemaRegistry is a helper method to define mock.On call
func (_e *MockServiceAddresses_Expecter) SchemaRegistry() *MockServiceAddresses_SchemaRegistry_Call {
	return &MockServiceAddresses_SchemaRegistry_Call{Call: _e.mock.On("SchemaRegistry")}
}

func (_c *MockServiceAddresses_SchemaRegistry_Call) Run(run func()) *MockServiceAddresses_SchemaRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceAddresses_SchemaRegistry_Call) Return(_a0 ServiceAddress) *MockServiceAddresses_SchemaRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceAddresses_SchemaRegistry_Call) RunAndReturn(run func() ServiceAddress) *MockServiceAddresses_SchemaRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// Valkey provides a mock function with no fields
func (_m *MockServiceAddresses) Valkey() ServiceAddress {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valkey")
	}

	var r0 ServiceAddress
	if rf, ok := ret.Get(0).(func() ServiceAddress); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServiceAddress)
	}

	return r0
}

// MockServiceAddresses_Valkey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valkey'
type MockServiceAddresses_Valkey_Call struct {
	*mock.Call
}

// Valkey is a helper method to define mock.On call
func (_e *MockServiceAddresses_Expecter) Valkey() *MockServiceAddresses_Valkey_Call {
	return &MockServiceAddresses_Valkey_Call{Call: _e.mock.On("Valkey")}
}

func (_c *MockServiceAddresses_Valkey_Call) Run(run func()) *MockServiceAddresses_Valkey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceAddresses_Valkey_Call) Return(_a0 ServiceAddress) *MockServiceAddresses_Valkey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceAddresses_Valkey_Call) RunAndReturn(run func() ServiceAddress) *MockServiceAddresses_Valkey_Call {
	_c.Call.Return(run)
	return _c
}

// ValkeyReplica provides a mock function with no fields
func (_m *MockServiceAddresses) ValkeyReplica() ServiceAddress {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValkeyReplica")
	}

	var r0 ServiceAddress
	if rf, ok := ret.Get(0).(func() ServiceAddress); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServiceAddress)
	}

	return r0
}

// MockServiceAddresses_ValkeyReplica_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValkeyReplica'
type MockServiceAddresses_ValkeyReplica_Call struct {
	*mock.Call
}

// ValkeyReplica is a helper method to define mock.On call
func (_e *MockServiceAddresses_Expecter) ValkeyReplica() *MockServiceAddresses_ValkeyReplica_Call {
	return &MockServiceAddresses_ValkeyReplica_Call{Call: _e.mock.On("ValkeyReplica")}
}

func (_c *MockServiceAddresses_ValkeyReplica_Call) Run(run func()) *MockServiceAddresses_ValkeyReplica_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceAddresses_ValkeyReplica_Call) Return(_a0 ServiceAddress) *MockServiceAddresses_ValkeyReplica_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceAddresses_ValkeyReplica_Call) RunAndReturn(run func() ServiceAddress) *MockServiceAddresses_ValkeyReplica_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceAddresses creates a new instance of MockServiceAddresses. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceAddresses(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceAddresses {
	mock := &MockServiceAddresses{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
