// Code generated by mockery v2.53.2. DO NOT EDIT.

package secret

import (
	context "context"

	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// MockSecrets is an autogenerated mock type for the Secrets type
type MockSecrets struct {
	mock.Mock
}

type MockSecrets_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecrets) EXPECT() *MockSecrets_Expecter {
	return &MockSecrets_Expecter{mock: &_m.Mock}
}

// GetOrInitSecret provides a mock function with given fields: ctx, namespace, secretName, logger
func (_m *MockSecrets) GetOrInitSecret(ctx context.Context, namespace string, secretName string, logger logrus.FieldLogger) v1.Secret {
	ret := _m.Called(ctx, namespace, secretName, logger)

	if len(ret) == 0 {
		panic("no return value specified for GetOrInitSecret")
	}

	var r0 v1.Secret
	if rf, ok := ret.Get(0).(func(context.Context, string, string, logrus.FieldLogger) v1.Secret); ok {
		r0 = rf(ctx, namespace, secretName, logger)
	} else {
		r0 = ret.Get(0).(v1.Secret)
	}

	return r0
}

// MockSecrets_GetOrInitSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrInitSecret'
type MockSecrets_GetOrInitSecret_Call struct {
	*mock.Call
}

// GetOrInitSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - secretName string
//   - logger logrus.FieldLogger
func (_e *MockSecrets_Expecter) GetOrInitSecret(ctx interface{}, namespace interface{}, secretName interface{}, logger interface{}) *MockSecrets_GetOrInitSecret_Call {
	return &MockSecrets_GetOrInitSecret_Call{Call: _e.mock.On("GetOrInitSecret", ctx, namespace, secretName, logger)}
}

func (_c *MockSecrets_GetOrInitSecret_Call) Run(run func(ctx context.Context, namespace string, secretName string, logger logrus.FieldLogger)) *MockSecrets_GetOrInitSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockSecrets_GetOrInitSecret_Call) Return(_a0 v1.Secret) *MockSecrets_GetOrInitSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecrets_GetOrInitSecret_Call) RunAndReturn(run func(context.Context, string, string, logrus.FieldLogger) v1.Secret) *MockSecrets_GetOrInitSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecrets creates a new instance of MockSecrets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecrets(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecrets {
	mock := &MockSecrets{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
