// Code generated by mockery. DO NOT EDIT.

package operator

import (
	context "context"

	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockServiceUserManager is an autogenerated mock type for the ServiceUserManager type
type MockServiceUserManager struct {
	mock.Mock
}

type MockServiceUserManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceUserManager) EXPECT() *MockServiceUserManager_Expecter {
	return &MockServiceUserManager_Expecter{mock: &_m.Mock}
}

// CreateServiceUser provides a mock function with given fields: ctx, owner, spec, logger
func (_m *MockServiceUserManager) CreateServiceUser(ctx context.Context, owner client.Object, spec ServiceUserSpec, logger logrus.FieldLogger) (*ServiceUser, error) {
	ret := _m.Called(ctx, owner, spec, logger)

	if len(ret) == 0 {
		panic("no return value specified for CreateServiceUser")
	}

	var r0 *ServiceUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Object, ServiceUserSpec, logrus.FieldLogger) (*ServiceUser, error)); ok {
		return rf(ctx, owner, spec, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Object, ServiceUserSpec, logrus.FieldLogger) *ServiceUser); ok {
		r0 = rf(ctx, owner, spec, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ServiceUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Object, ServiceUserSpec, logrus.FieldLogger) error); ok {
		r1 = rf(ctx, owner, spec, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceUserManager_CreateServiceUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServiceUser'
type MockServiceUserManager_CreateServiceUser_Call struct {
	*mock.Call
}

// CreateServiceUser is a helper method to define mock.On call
//   - ctx context.Context
//   - owner client.Object
//   - spec ServiceUserSpec
//   - logger logrus.FieldLogger
func (_e *MockServiceUserManager_Expecter) CreateServiceUser(ctx interface{}, owner interface{}, spec interface{}, logger interface{}) *MockServiceUserManager_CreateServiceUser_Call {
	return &MockServiceUserManager_CreateServiceUser_Call{Call: _e.mock.On("CreateServiceUser", ctx, owner, spec, logger)}
}

func (_c *MockServiceUserManager_CreateServiceUser_Call) Run(run func(ctx context.Context, owner client.Object, spec ServiceUserSpec, logger logrus.FieldLogger)) *MockServiceUserManager_CreateServiceUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Object), args[2].(ServiceUserSpec), args[3].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockServiceUserManager_CreateServiceUser_Call) Return(_a0 *ServiceUser, _a1 error) *MockServiceUserManager_CreateServiceUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceUserManager_CreateServiceUser_Call) RunAndReturn(run func(context.Context, client.Object, ServiceUserSpec, logrus.FieldLogger) (*ServiceUser, error)) *MockServiceUserManager_CreateServiceUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServiceUser provides a mock function with given fields: ctx, namespace, name, logger
func (_m *MockServiceUserManager) DeleteServiceUser(ctx context.Context, namespace string, name string, logger logrus.FieldLogger) error {
	ret := _m.Called(ctx, namespace, name, logger)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, logrus.FieldLogger) error); ok {
		r0 = rf(ctx, namespace, name, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceUserManager_DeleteServiceUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServiceUser'
type MockServiceUserManager_DeleteServiceUser_Call struct {
	*mock.Call
}

// DeleteServiceUser is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - logger logrus.FieldLogger
func (_e *MockServiceUserManager_Expecter) DeleteServiceUser(ctx interface{}, namespace interface{}, name interface{}, logger interface{}) *MockServiceUserManager_DeleteServiceUser_Call {
	return &MockServiceUserManager_DeleteServiceUser_Call{Call: _e.mock.On("DeleteServiceUser", ctx, namespace, name, logger)}
}

func (_c *MockServiceUserManager_DeleteServiceUser_Call) Run(run func(ctx context.Context, namespace string, name string, logger logrus.FieldLogger)) *MockServiceUserManager_DeleteServiceUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockServiceUserManager_DeleteServiceUser_Call) Return(_a0 error) *MockServiceUserManager_DeleteServiceUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceUserManager_DeleteServiceUser_Call) RunAndReturn(run func(context.Context, string, string, logrus.FieldLogger) error) *MockServiceUserManager_DeleteServiceUser_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, namespace, name
func (_m *MockServiceUserManager) Exists(ctx context.Context, namespace string, name string) (bool, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceUserManager_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockServiceUserManager_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockServiceUserManager_Expecter) Exists(ctx interface{}, namespace interface{}, name interface{}) *MockServiceUserManager_Exists_Call {
	return &MockServiceUserManager_Exists_Call{Call: _e.mock.On("Exists", ctx, namespace, name)}
}

func (_c *MockServiceUserManager_Exists_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockServiceUserManager_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceUserManager_Exists_Call) Return(_a0 bool, _a1 error) *MockServiceUserManager_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceUserManager_Exists_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockServiceUserManager_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindAdoptable provides a mock function with given fields: ctx, namespace, appName, familyPrefix, serviceName, logger
func (_m *MockServiceUserManager) FindAdoptable(ctx context.Context, namespace string, appName string, familyPrefix string, serviceName string, logger logrus.FieldLogger) (string, error) {
	ret := _m.Called(ctx, namespace, appName, familyPrefix, serviceName, logger)

	if len(ret) == 0 {
		panic("no return value specified for FindAdoptable")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, logrus.FieldLogger) (string, error)); ok {
		return rf(ctx, namespace, appName, familyPrefix, serviceName, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, logrus.FieldLogger) string); ok {
		r0 = rf(ctx, namespace, appName, familyPrefix, serviceName, logger)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, logrus.FieldLogger) error); ok {
		r1 = rf(ctx, namespace, appName, familyPrefix, serviceName, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceUserManager_FindAdoptable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAdoptable'
type MockServiceUserManager_FindAdoptable_Call struct {
	*mock.Call
}

// FindAdoptable is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - appName string
//   - familyPrefix string
//   - serviceName string
//   - logger logrus.FieldLogger
func (_e *MockServiceUserManager_Expecter) FindAdoptable(ctx interface{}, namespace interface{}, appName interface{}, familyPrefix interface{}, serviceName interface{}, logger interface{}) *MockServiceUserManager_FindAdoptable_Call {
	return &MockServiceUserManager_FindAdoptable_Call{Call: _e.mock.On("FindAdoptable", ctx, namespace, appName, familyPrefix, serviceName, logger)}
}

func (_c *MockServiceUserManager_FindAdoptable_Call) Run(run func(ctx context.Context, namespace string, appName string, familyPrefix string, serviceName string, logger logrus.FieldLogger)) *MockServiceUserManager_FindAdoptable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockServiceUserManager_FindAdoptable_Call) Return(_a0 string, _a1 error) *MockServiceUserManager_FindAdoptable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceUserManager_FindAdoptable_Call) RunAndReturn(run func(context.Context, string, string, string, string, logrus.FieldLogger) (string, error)) *MockServiceUserManager_FindAdoptable_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceName provides a mock function with given fields: ctx, namespace, name
func (_m *MockServiceUserManager) ServiceName(ctx context.Context, namespace string, name string) (string, bool, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for ServiceName")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, bool, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, namespace, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockServiceUserManager_ServiceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceName'
type MockServiceUserManager_ServiceName_Call struct {
	*mock.Call
}

// ServiceName is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockServiceUserManager_Expecter) ServiceName(ctx interface{}, namespace interface{}, name interface{}) *MockServiceUserManager_ServiceName_Call {
	return &MockServiceUserManager_ServiceName_Call{Call: _e.mock.On("ServiceName", ctx, namespace, name)}
}

func (_c *MockServiceUserManager_ServiceName_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockServiceUserManager_ServiceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceUserManager_ServiceName_Call) Return(_a0 string, _a1 bool, _a2 error) *MockServiceUserManager_ServiceName_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockServiceUserManager_ServiceName_Call) RunAndReturn(run func(context.Context, string, string) (string, bool, error)) *MockServiceUserManager_ServiceName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceUserManager creates a new instance of MockServiceUserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceUserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceUserManager {
	mock := &MockServiceUserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
