// Code generated by mockery. DO NOT EDIT.

package operator

import (
	context "context"

	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockOpenSearchACLManager is an autogenerated mock type for the OpenSearchACLManager type
type MockOpenSearchACLManager struct {
	mock.Mock
}

type MockOpenSearchACLManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenSearchACLManager) EXPECT() *MockOpenSearchACLManager_Expecter {
	return &MockOpenSearchACLManager_Expecter{mock: &_m.Mock}
}

// CreateServiceUserACLs provides a mock function with given fields: ctx, instance, spec, logger
func (_m *MockOpenSearchACLManager) CreateServiceUserACLs(ctx context.Context, instance client.Object, spec OpenSearchACLSpec, logger logrus.FieldLogger) error {
	ret := _m.Called(ctx, instance, spec, logger)

	if len(ret) == 0 {
		panic("no return value specified for CreateServiceUserACLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Object, OpenSearchACLSpec, logrus.FieldLogger) error); ok {
		r0 = rf(ctx, instance, spec, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOpenSearchACLManager_CreateServiceUserACLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServiceUserACLs'
type MockOpenSearchACLManager_CreateServiceUserACLs_Call struct {
	*mock.Call
}

// CreateServiceUserACLs is a helper method to define mock.On call
//   - ctx context.Context
//   - instance client.Object
//   - spec OpenSearchACLSpec
//   - logger logrus.FieldLogger
func (_e *MockOpenSearchACLManager_Expecter) CreateServiceUserACLs(ctx interface{}, instance interface{}, spec interface{}, logger interface{}) *MockOpenSearchACLManager_CreateServiceUserACLs_Call {
	return &MockOpenSearchACLManager_CreateServiceUserACLs_Call{Call: _e.mock.On("CreateServiceUserACLs", ctx, instance, spec, logger)}
}

func (_c *MockOpenSearchACLManager_CreateServiceUserACLs_Call) Run(run func(ctx context.Context, instance client.Object, spec OpenSearchACLSpec, logger logrus.FieldLogger)) *MockOpenSearchACLManager_CreateServiceUserACLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Object), args[2].(OpenSearchACLSpec), args[3].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockOpenSearchACLManager_CreateServiceUserACLs_Call) Return(_a0 error) *MockOpenSearchACLManager_CreateServiceUserACLs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOpenSearchACLManager_CreateServiceUserACLs_Call) RunAndReturn(run func(context.Context, client.Object, OpenSearchACLSpec, logrus.FieldLogger) error) *MockOpenSearchACLManager_CreateServiceUserACLs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServiceUserACLs provides a mock function with given fields: ctx, namespace, serviceName, username, logger
func (_m *MockOpenSearchACLManager) DeleteServiceUserACLs(ctx context.Context, namespace string, serviceName string, username string, logger logrus.FieldLogger) error {
	ret := _m.Called(ctx, namespace, serviceName, username, logger)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceUserACLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, logrus.FieldLogger) error); ok {
		r0 = rf(ctx, namespace, serviceName, username, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOpenSearchACLManager_DeleteServiceUserACLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServiceUserACLs'
type MockOpenSearchACLManager_DeleteServiceUserACLs_Call struct {
	*mock.Call
}

// DeleteServiceUserACLs is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - serviceName string
//   - username string
//   - logger logrus.FieldLogger
func (_e *MockOpenSearchACLManager_Expecter) DeleteServiceUserACLs(ctx interface{}, namespace interface{}, serviceName interface{}, username interface{}, logger interface{}) *MockOpenSearchACLManager_DeleteServiceUserACLs_Call {
	return &MockOpenSearchACLManager_DeleteServiceUserACLs_Call{Call: _e.mock.On("DeleteServiceUserACLs", ctx, namespace, serviceName, username, logger)}
}

func (_c *MockOpenSearchACLManager_DeleteServiceUserACLs_Call) Run(run func(ctx context.Context, namespace string, serviceName string, username string, logger logrus.FieldLogger)) *MockOpenSearchACLManager_DeleteServiceUserACLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockOpenSearchACLManager_DeleteServiceUserACLs_Call) Return(_a0 error) *MockOpenSearchACLManager_DeleteServiceUserACLs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOpenSearchACLManager_DeleteServiceUserACLs_Call) RunAndReturn(run func(context.Context, string, string, string, logrus.FieldLogger) error) *MockOpenSearchACLManager_DeleteServiceUserACLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOpenSearchACLManager creates a new instance of MockOpenSearchACLManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenSearchACLManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenSearchACLManager {
	mock := &MockOpenSearchACLManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
