// Code generated by mockery v2.7.4. DO NOT EDIT.

package certificate

import mock "github.com/stretchr/testify/mock"

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

// MakeCredStores provides a mock function with given fields: accessKey, accessCert, caCert
func (_m *MockGenerator) MakeCredStores(accessKey string, accessCert string, caCert string) (*CredStoreData, error) {
	ret := _m.Called(accessKey, accessCert, caCert)

	var r0 *CredStoreData
	if rf, ok := ret.Get(0).(func(string, string, string) *CredStoreData); ok {
		r0 = rf(accessKey, accessCert, caCert)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CredStoreData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(accessKey, accessCert, caCert)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
