apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "redis-test"
  namespace: basseng
  labels:
    team: "basseng"
spec:
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/kafka-debug:2025-01-22-132723-a7c7314
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  valkey:
    - instance: cache
      access: admin
