apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "aivia-test"
  namespace: default
  labels:
    team: "aura"
spec:
  image: nginx:latest
  liveness:
    path: "/"
    port: 80
  readiness:
    path: "/"
    port: 80
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  kafka:
    pool: nav-integration-test
  skipCaBundle: true
