{
 "title": "Status in $ds",
 "panels": [
  {
   "title": "Healthy",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"aivenator\", namespace=\"nais-system\"})"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{container=\"aivenator\", namespace=\"nais-system\"})"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\",namespace=\"nais-system\",pod=~\"^aivenator-.+\"})"
    }
   ]
  },
  {
   "title": "# of restarts",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"aivenator\", namespace=\"nais-system\"})"
    }
   ]
  },
  {
   "title": "App version",
   "type": "singlestat",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(kube_pod_container_info{container=\"aivenator\",namespace=\"nais-system\"}, \"version\", \"$1\", \"image\", \".*:(.*)\")",
     "legendFormat": "{{ version }}"
    }
   ]
  }
 ]
}
{
 "title": "Applications",
 "panels": [
  {
   "title": "AivenApplications processed - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_aiven_applications_processed) by (synchronization_state)",
     "legendFormat": "{{ synchronization_state }}"
    }
   ]
  },
  {
   "title": "AivenApplications requeued - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_aiven_applications_requeued) by (synchronization_state)",
     "legendFormat": "{{ synchronization_state }}"
    }
   ]
  },
  {
   "title": "Processing time - $ds",
   "type": "heatmap",
   "repeat": "ds",
   "targets": [
    {
     "expr": "sum(increase(aivenator_aiven_application_processing_time_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}
{
 "title": "Resource usage",
 "panels": [
  {
   "title": "Memory usage - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"nais-system\",container=\"aivenator\",resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"nais-system\",container=\"aivenator\",resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"nais-system\",container=\"aivenator\"}) by (pod)",
     "legendFormat": "working set {{ pod }}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"nais-system\",container=\"aivenator\"}) by (pod)",
     "legendFormat": "Resident set size {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU usage - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"nais-system\",container=\"aivenator\",resource=\"cpu\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"nais-system\",container=\"aivenator\",resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"aivenator\",namespace=\"nais-system\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Aiven operations",
 "panels": [
  {
   "title": "ServiceUsers created - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_service_users_created) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "ServiceUsers deleted - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_service_users_deleted) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes operations",
 "panels": [
  {
   "title": "Resources written - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_kubernetes_resources_written) by (resource_type)",
     "legendFormat": "{{ resource_type }}"
    }
   ]
  },
  {
   "title": "Resources deleted - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_kubernetes_resources_deleted) by (resource_type)",
     "legendFormat": "{{ resource_type }}"
    }
   ]
  },
  {
   "title": "Protected Secrets - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_secrets_managed{state=\"protected\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Managed Secrets (in use) - $ds",
   "type": "graph",
   "repeat": "ds",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aivenator_secrets_managed{state=\"in_use\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Latency - $kube_op",
 "panels": [
  {
   "title": "$ds",
   "type": "heatmap",
   "repeat": "ds",
   "targets": [
    {
     "expr": "sum(increase(aivenator_kubernetes_latency_bucket{operation=\"$kube_op\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}
{
 "title": "Aiven Latency - $aiven_op",
 "panels": [
  {
   "title": "$ds",
   "type": "heatmap",
   "repeat": "ds",
   "targets": [
    {
     "expr": "sum(increase(aivenator_aiven_latency_bucket{operation=\"$aiven_op\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}