apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kafka-test
  namespace: basseng
spec:
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/kafka-debug:latest
  kafka:
    pool: dev-nais-dev
