apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: opensearch-test
  namespace: basseng
spec:
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/kafka-debug:latest
  openSearch:
    instance: test
    access: read
