// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	aiven "github.com/aiven/aiven-go-client"
	mock "github.com/stretchr/testify/mock"
)

// ServiceManager is an autogenerated mock type for the ServiceManager type
type ServiceManager struct {
	mock.Mock
}

// Get provides a mock function with given fields: projectName, serviceName
func (_m *ServiceManager) Get(projectName string, serviceName string) (*aiven.Service, error) {
	ret := _m.Called(projectName, serviceName)

	var r0 *aiven.Service
	if rf, ok := ret.Get(0).(func(string, string) *aiven.Service); ok {
		r0 = rf(projectName, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(projectName, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCA provides a mock function with given fields: projectName
func (_m *ServiceManager) GetCA(projectName string) (string, error) {
	ret := _m.Called(projectName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(projectName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
