// Code generated by mockery v2.53.2. DO NOT EDIT.

package credentials

import (
	context "context"

	aiven_nais_io_v2 "github.com/nais/liberator/pkg/apis/aiven.nais.io/v2"

	logrus "github.com/sirupsen/logrus"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// MockServiceHandler is an autogenerated mock type for the ServiceHandler type
type MockServiceHandler struct {
	mock.Mock
}

type MockServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceHandler) EXPECT() *MockServiceHandler_Expecter {
	return &MockServiceHandler_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, application, logger
func (_m *MockServiceHandler) Apply(ctx context.Context, application *aiven_nais_io_v2.AivenApplication, logger logrus.FieldLogger) ([]v1.Secret, error) {
	ret := _m.Called(ctx, application, logger)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 []v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *aiven_nais_io_v2.AivenApplication, logrus.FieldLogger) ([]v1.Secret, error)); ok {
		return rf(ctx, application, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *aiven_nais_io_v2.AivenApplication, logrus.FieldLogger) []v1.Secret); ok {
		r0 = rf(ctx, application, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *aiven_nais_io_v2.AivenApplication, logrus.FieldLogger) error); ok {
		r1 = rf(ctx, application, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceHandler_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockServiceHandler_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - application *aiven_nais_io_v2.AivenApplication
//   - logger logrus.FieldLogger
func (_e *MockServiceHandler_Expecter) Apply(ctx interface{}, application interface{}, logger interface{}) *MockServiceHandler_Apply_Call {
	return &MockServiceHandler_Apply_Call{Call: _e.mock.On("Apply", ctx, application, logger)}
}

func (_c *MockServiceHandler_Apply_Call) Run(run func(ctx context.Context, application *aiven_nais_io_v2.AivenApplication, logger logrus.FieldLogger)) *MockServiceHandler_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*aiven_nais_io_v2.AivenApplication), args[2].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockServiceHandler_Apply_Call) Return(_a0 []v1.Secret, _a1 error) *MockServiceHandler_Apply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceHandler_Apply_Call) RunAndReturn(run func(context.Context, *aiven_nais_io_v2.AivenApplication, logrus.FieldLogger) ([]v1.Secret, error)) *MockServiceHandler_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function with given fields: ctx, secret, logger
func (_m *MockServiceHandler) Cleanup(ctx context.Context, secret *v1.Secret, logger logrus.FieldLogger) error {
	ret := _m.Called(ctx, secret, logger)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Secret, logrus.FieldLogger) error); ok {
		r0 = rf(ctx, secret, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceHandler_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockServiceHandler_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *v1.Secret
//   - logger logrus.FieldLogger
func (_e *MockServiceHandler_Expecter) Cleanup(ctx interface{}, secret interface{}, logger interface{}) *MockServiceHandler_Cleanup_Call {
	return &MockServiceHandler_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx, secret, logger)}
}

func (_c *MockServiceHandler_Cleanup_Call) Run(run func(ctx context.Context, secret *v1.Secret, logger logrus.FieldLogger)) *MockServiceHandler_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Secret), args[2].(logrus.FieldLogger))
	})
	return _c
}

func (_c *MockServiceHandler_Cleanup_Call) Return(_a0 error) *MockServiceHandler_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceHandler_Cleanup_Call) RunAndReturn(run func(context.Context, *v1.Secret, logrus.FieldLogger) error) *MockServiceHandler_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceHandler creates a new instance of MockServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceHandler {
	mock := &MockServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
