apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: { { include "aivenator.fullname" . } }
  labels: { { - include "aivenator.labels" . | nindent 4 } }
spec:
  egress:
    - to:
        - ipBlock:
            cidr: "0.0.0.0/0"
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector:
    matchLabels: { { - include "aivenator.selectorLabels" . | nindent 6 } }
  policyTypes:
    - Egress
