apiVersion: v1
kind: Secret
metadata:
  name: { { include "aivenator.fullname" . } }
  labels: { { - include "aivenator.labels" . | nindent 4 } }
stringData:
  AIVENATOR_AIVEN_TOKEN: { { .Values.aiven.token | quote } }
