apiVersion: v1
kind: Service
metadata:
  name: { { include "aivenator.fullname" . } }
  labels: { { - include "aivenator.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "aivenator.selectorLabels" . | nindent 4 } }
