---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "aivenator.serviceAccountName" . } }
  labels: { { - include "aivenator.labels" . | nindent 4 } }

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: { { include "aivenator.fullname" . } }
  labels: { { - include "aivenator.labels" . | nindent 4 } }
rules:
  - apiGroups:
      - aiven.nais.io
    resources:
      - aivenapplications
      - aivenapplications/status
    verbs:
      - get
      - list
      - watch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: { { include "aivenator.fullname" . } }
  labels: { { - include "aivenator.labels" . | nindent 4 } }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: { { include "aivenator.fullname" . } }
subjects:
  - kind: ServiceAccount
    name: { { include "aivenator.serviceAccountName" . } }
    namespace: "{{ .Release.Namespace }}"
