// Code generated by mockery v2.7.4. DO NOT EDIT.

package serviceuser

import (
	aiven "github.com/aiven/aiven-go-client"
	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: project, service, req
func (_m *MockInterface) Create(project string, service string, req aiven.CreateServiceUserRequest) (*aiven.ServiceUser, error) {
	ret := _m.Called(project, service, req)

	var r0 *aiven.ServiceUser
	if rf, ok := ret.Get(0).(func(string, string, aiven.CreateServiceUserRequest) *aiven.ServiceUser); ok {
		r0 = rf(project, service, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.ServiceUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, aiven.CreateServiceUserRequest) error); ok {
		r1 = rf(project, service, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
