[env]
_.source = ".config/mise/extract_env.sh"
AIVENATOR_IMAGE = "europe-north1-docker.pkg.dev/nais-io/nais/images/aivenator:latest"
AIVENATOR_TTL_IMAGE = "ttl.sh/aivenator:1h"

[tools]
setup-envtest = """
{%- set tool = '"\\\\ssigs.k8s.io/controller-runtime\\\\s"' -%}
{%- set version_fmt = '"%d.%d"' -%}
{%- set command = "grep " ~ tool ~ " " ~ config_root ~ "/go.mod | awk -F. '{printf " ~ version_fmt ~ ", $3, $4}'" -%}

{{- exec(cache_key="setup-envtest", command=command) -}}
"""
go = """
{%- set command = 'grep "^go [0-9]*\\\\.[0-9]*" ' ~ config_root ~ "/go.mod | awk '{print $2}'" -%}

{{- exec(cache_key="go", command=command) -}}
"""

[tasks."check"]
description = "Run all checks"
run = [
    {"task"= "check:*"}
]

[tasks."check:deadcode"]
description = "Run deadcode"
run = "go tool golang.org/x/tools/cmd/deadcode -test -tags=integration ./..."

#[tasks."check:gosec"]
#description = "Run gosec"
#run = "go tool github.com/securego/gosec/v2/cmd/gosec --exclude-generated -terse ./..."

[tasks."check:staticcheck"]
description = "Run staticcheck"
run = "go tool honnef.co/go/tools/cmd/staticcheck ./..."

[tasks."check:vulncheck"]
description = "Run vulncheck"
run = "go tool golang.org/x/vuln/cmd/govulncheck ./..."

[tasks."check:zizmor"]
description = "Run zizmor"
tools = {"uv"="latest"}
run = "uvx zizmor ."

[tasks."fmt"]
description = "Format all code"
run = [
    {"task"= "fmt:*"}
]

[tasks."fmt:go"]
description = "Format go code using gofumpt"
run = "go tool mvdan.cc/gofumpt -w ./"

[tasks."fmt:gofix"]
description = "Fix runs the Go fix tool (cmd/fix) on the named packages and applies suggested fixes."
run = "go fix ./..."

[tasks."test"]
description = "Test Go code"
run = "go test ./..."

[tasks."update:tools"]
description = "Update all Go tools to latest"
run = """
go list tool | xargs go get -tool
go mod tidy
"""
